import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#020617",
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#020617",
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: "#f9fafb",
    marginBottom: 8,
  },
  avatarCard: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#0f172a",
    marginBottom: 12,
  },
  avatarHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  avatarName: {
    color: "#e5e7eb",
    fontWeight: "600",
  },
  avatarLevel: {
    color: "#e5e7eb",
    fontWeight: "700",
    fontSize: 18,
    marginBottom: 4,
  },
  progressBar: {
    width: "100%",
    height: 8,
    borderRadius: 999,
    backgroundColor: "#1f2937",
    overflow: "hidden",
    marginTop: 4,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#22c55e",
  },
  block: {
    marginTop: 12,
  },
  blockRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 12,
  },
  expCol: {
    width: "48%",
    marginBottom: 8,
  },
  label: {
    color: "#9ca3af",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  muted: {
    color: "#9ca3af",
    fontSize: 13,
  },
  primaryBtn: {
    marginTop: 16,
    backgroundColor: "#4f46e5",
    borderRadius: 999,
    paddingVertical: 10,
    alignItems: "center",
  },
  primaryBtnText: {
    color: "#f9fafb",
    fontWeight: "600",
    fontSize: 16,
  },
  secondaryBtn: {
    marginTop: 12,
    backgroundColor: "#0f172a",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#4f46e5",
  },
  secondaryBtnText: {
    color: "#e5e7eb",
    fontWeight: "500",
  },
  dangerBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#7f1d1d",
  },
  dangerBtnText: {
    color: "#fecaca",
    fontWeight: "500",
  },
  ghostBtn: {
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  ghostBtnText: {
    color: "#9ca3af",
  },
  iconBtn: {
    width: 32,
    height: 32,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#4b5563",
    alignItems: "center",
    justifyContent: "center",
  },
  iconBtnText: {
    color: "#e5e7eb",
    fontSize: 18,
    marginTop: -2,
  },
  textArea: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1f2937",
    padding: 8,
    color: "#e5e7eb",
    minHeight: 80,
  },
  input: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#1f2937",
    padding: 8,
    color: "#e5e7eb",
    marginTop: 4,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  inputGrow: {
    flex: 1,
  },
  rowWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 12,
  },
  chip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#4b5563",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  chipActive: {
    borderColor: "#4f46e5",
    backgroundColor: "#111827",
  },
  chipHighlighted: {
    borderColor: "#f59e0b",
    backgroundColor: "#78350f",
  },
  chipText: {
    color: "#e5e7eb",
    fontSize: 13,
  },
  error: {
    color: "#f97316",
    marginTop: 4,
  },
  timerBlock: {
    alignItems: "center",
    marginVertical: 32,
  },
  sessionEmoji: {
    fontSize: 48,
    marginBottom: 8,
  },
  timerText: {
    fontSize: 40,
    fontWeight: "700",
    color: "#f9fafb",
    letterSpacing: 4,
  },
  sessionTitle: {
    marginTop: 8,
    fontSize: 18,
    color: "#e5e7eb",
    textAlign: "center",
  },
  summary: {
    marginTop: 8,
    color: "#e5e7eb",
  },
  sectionTitle: {
    color: "#f9fafb",
    fontSize: 18,
    fontWeight: "600",
  },
  historyItem: {
    marginTop: 6,
  },
  historyPrimary: {
    color: "#e5e7eb",
  },
  historyNotes: {
    color: "#9ca3af",
    fontStyle: "italic",
    fontSize: 12,
  },
  expValue: {
    color: "#fbbf24",
    fontWeight: "600",
    marginTop: 2,
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: 8,
  },
  logControls: {
    alignItems: "flex-end",
    gap: 4,
  },
  copiedToast: {
    marginTop: 4,
    color: "#22c55e",
    fontSize: 12,
  },
  questList: {
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  questItem: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "#020617",
    borderWidth: 1,
    borderColor: "#1f2937",
    marginRight: 8,
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  questItemActive: {
    borderColor: "#4f46e5",
    backgroundColor: "#1e1b4b",
  },
  questItemHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  questItemLabel: {
    color: "#e5e7eb",
    fontSize: 13,
    fontWeight: "500",
  },
  questItemMeta: {
    color: "#9ca3af",
    fontSize: 11,
    marginLeft: 4,
  },
  questItemUser: {
    // No special styling - user quests look like regular quests
  },
  questItemUserBadge: {
    display: "none",
  },
  // Apple-search-style quest suggestion grid
  questGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
  questGridItem: {
    backgroundColor: "#0f172a",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#1f2937",
    minWidth: 90,
    maxWidth: 140,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  questGridItemActive: {
    borderColor: "#4f46e5",
    backgroundColor: "#1e1b4b",
    ...(Platform.OS === "web"
      ? { boxShadow: "0px 0px 8px rgba(79,70,229,0.4)" }
      : {
          shadowColor: "#4f46e5",
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.4,
          shadowRadius: 8,
        }),
    elevation: 4,
  },
  questGridItemUser: {
    borderColor: "#2563eb",
  },
  questGridItemText: {
    color: "#e5e7eb",
    fontSize: 13,
    fontWeight: "500",
    textAlign: "center",
  },
  questGridBadge: {
    position: "absolute",
    top: 4,
    right: 6,
    fontSize: 10,
    color: "#fbbf24",
  },
  questActionsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  actionBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: "#1e3a5f",
  },
  actionBtnText: {
    color: "#93c5fd",
    fontSize: 13,
  },
  editBtn: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: "#374151",
  },
  editBtnText: {
    color: "#e5e7eb",
    fontSize: 13,
  },
  scrollContent: {
    paddingBottom: 40,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  optional: {
    color: "#6b7280",
    fontSize: 11,
  },
  durationRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 6,
  },
  durationChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#0f172a",
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  durationChipActive: {
    borderColor: "#4f46e5",
    backgroundColor: "#1e1b4b",
  },
  durationChipText: {
    color: "#9ca3af",
    fontSize: 14,
    fontWeight: "500",
  },
  durationChipTextActive: {
    color: "#e5e7eb",
  },
  durationInput: {
    width: 70,
    textAlign: "center",
    marginTop: 0,
  },
  actionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 24,
    paddingBottom: 20,
  },
  actionsRight: {
    flexDirection: "row",
    gap: 10,
  },
  resetLink: {
    alignSelf: "center",
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  resetLinkText: {
    color: "#6b7280",
    fontSize: 12,
    textDecorationLine: "underline",
  },
  durationSection: {
    marginTop: 4,
    alignItems: "center",
  },
  homeContainer: {
    flex: 1,
    backgroundColor: "#020617",
    paddingHorizontal: 16,
    position: "relative",
  },
  announcements: {
    marginTop: 8,
    gap: 8,
  },
  announcementCard: {
    backgroundColor: "#0f172a",
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  announcementTitle: {
    color: "#fbbf24",
    fontWeight: "700",
    fontSize: 14,
  },
  announcementBody: {
    color: "#e5e7eb",
    marginTop: 2,
    fontSize: 12,
  },
  homeHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
  },
  headerUsername: {
    color: "#f9fafb",
    fontSize: 18,
    fontWeight: "700",
    flex: 1,
  },
  headerCenter: {
    alignItems: "center",
    flex: 1,
  },
  headerLevel: {
    color: "#fbbf24",
    fontSize: 16,
    fontWeight: "700",
  },
  headerTitle: {
    color: "#9ca3af",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  headerIcons: {
    flexDirection: "row",
    gap: 8,
    flex: 1,
    justifyContent: "flex-end",
  },
  headerIconBtn: {
    padding: 8,
  },
  headerIcon: {
    fontSize: 20,
  },
  notificationDropdownContainer: {
    position: "absolute",
    top: 44,
    right: 12,
    zIndex: 30,
    alignItems: "flex-end",
  },
  notificationBackdrop: {
    position: "absolute",
    top: 48,
    left: 0,
    right: 0,
    bottom: 0,
  },
  notificationDropdown: {
    marginTop: 4,
    width: 320,
    maxWidth: "100%",
    backgroundColor: "#0b1220",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1f2937",
    padding: 12,
    ...(Platform.OS === "web"
      ? { boxShadow: "0px 6px 10px rgba(0,0,0,0.3)" }
      : {
          shadowColor: "#000",
          shadowOpacity: 0.3,
          shadowRadius: 10,
          shadowOffset: { width: 0, height: 6 },
        }),
    elevation: 8,
  },
  notificationDropdownHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  notificationDropdownTitle: {
    color: "#e5e7eb",
    fontSize: 14,
    fontWeight: "700",
  },
  notificationCloseBtn: {
    padding: 6,
  },
  notificationCloseIcon: {
    color: "#9ca3af",
    fontSize: 14,
  },
  notificationList: {
    maxHeight: 260,
  },
  sheetBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  sheetTopContainer: {
    position: "absolute",
    left: 0,
    right: 0,
    backgroundColor: "#0b1220",
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderWidth: 1,
    borderColor: "#1f2937",
    borderTopWidth: 0,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 18,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#334155",
    marginBottom: 10,
  },
  sheetHandleBottom: {
    alignSelf: "center",
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: "#334155",
    marginTop: 12,
  },
  sheetHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  sheetTitle: {
    color: "#e5e7eb",
    fontSize: 16,
    fontWeight: "800",
  },
  sheetCloseBtn: {
    padding: 8,
  },
  sheetCloseIcon: {
    color: "#9ca3af",
    fontSize: 16,
    fontWeight: "700",
  },
  sheetList: {
    maxHeight: 340,
  },
  sheetEmpty: {
    color: "#6b7280",
    fontSize: 13,
    paddingVertical: 10,
  },
  toastContainer: {
    position: "absolute",
    bottom: 90,
    alignSelf: "center",
    backgroundColor: "rgba(15,23,42,0.9)",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  toastText: {
    color: "#f9fafb",
    fontSize: 13,
    fontWeight: "600",
  },
  stage: {
    position: "relative",
    width: "100%",
    marginVertical: 8,
    overflow: "hidden",
    minHeight: 220,
  },
  chartBackground: {
    position: "absolute",
    top: 0,
    right: 0,
    opacity: 0.9,
    padding: 4,
    alignItems: "flex-end",
    pointerEvents: "none",
  },
  roamingAvatar: {
    position: "absolute",
    zIndex: 10,
  },
  quoteBubble: {
    position: "absolute",
    backgroundColor: "#1e1b4b",
    borderRadius: 12,
    padding: 10,
    maxWidth: 180,
    zIndex: 5,
    borderWidth: 2,
    borderColor: "#4f46e5",
  },
  quoteBubbleText: {
    color: "#e5e7eb",
    fontSize: 12,
    fontStyle: "italic",
    lineHeight: 16,
  },
  quoteBubbleTail: {
    position: "absolute",
    bottom: -8,
    left: 18,
    width: 0,
    height: 0,
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderTopWidth: 8,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderTopColor: "#4f46e5",
    transform: [{ rotate: "-20deg" }],
  },
  expProgressSection: {
    marginBottom: 16,
  },
  expText: {
    color: "#9ca3af",
    fontSize: 12,
    textAlign: "center",
    marginTop: 6,
  },
  quickstartCard: {
    backgroundColor: "#0f172a",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#1f2937",
    marginBottom: 8,
    gap: 8,
  },
  quickstartHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  quickstartMode: {
    color: "#6b7280",
    fontSize: 12,
  },
  quickstartBtn: {
    backgroundColor: "#4f46e5",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
  },
  quickstartBtnText: {
    color: "#f9fafb",
    fontWeight: "600",
    fontSize: 15,
  },
  quickstartSuggestions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  quickstartChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "#111827",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  quickstartChipLabel: {
    color: "#e5e7eb",
    fontSize: 13,
    fontWeight: "600",
  },
  quickstartChipMeta: {
    color: "#9ca3af",
    fontSize: 12,
  },
  quoteSection: {
    backgroundColor: "#0f172a",
    borderRadius: 12,
    padding: 16,
    marginTop: 8,
    borderLeftWidth: 3,
    borderLeftColor: "#4f46e5",
  },
  quoteText: {
    color: "#e5e7eb",
    fontSize: 14,
    fontStyle: "italic",
    lineHeight: 22,
  },
  homeFooter: {
    gap: 12,
    marginTop: 8,
  },
  homeFooterSection: {
    backgroundColor: "#0f172a",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#1f2937",
    gap: 8,
  },
  homeFooterHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  footerMeta: {
    color: "#9ca3af",
    fontSize: 12,
  },
  footerEmpty: {
    color: "#6b7280",
    fontSize: 12,
  },
  footerItem: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
  },
  footerItemTitle: {
    color: "#e5e7eb",
    fontSize: 14,
    fontWeight: "600",
  },
  footerItemMeta: {
    color: "#9ca3af",
    fontSize: 12,
    marginTop: 2,
  },
  navbar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    backgroundColor: "#0f172a",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderTopWidth: 1,
    borderTopColor: "#1f2937",
  },
  navItem: {
    alignItems: "center",
    paddingVertical: 4,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  navItemActive: {
    backgroundColor: "#1e1b4b",
  },
  navIcon: {
    fontSize: 20,
    marginBottom: 2,
  },
  navLabel: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "500",
  },
  navLabelActive: {
    color: "#a5b4fc",
  },
  navBigButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#4f46e5",
    alignItems: "center",
    justifyContent: "center",
    // Lift above the tab bar, like a centered action button on iOS.
    transform: [{ translateY: -20 }],
    ...(Platform.OS === "web"
      ? { boxShadow: "0px 4px 8px rgba(79,70,229,0.4)" }
      : {
          shadowColor: "#4f46e5",
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.4,
          shadowRadius: 8,
        }),
    elevation: 8,
    borderWidth: 3,
    borderColor: "#0b1220",
  },
  navBigButtonIcon: {
    fontSize: 28,
  },
  screenContainer: {
    flex: 1,
    backgroundColor: "#020617",
    paddingHorizontal: 16,
  },
  screenHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
  },
  screenTitle: {
    color: "#f9fafb",
    fontSize: 20,
    fontWeight: "700",
  },
  backBtn: {
    color: "#a5b4fc",
    fontSize: 16,
  },
  addBtn: {
    backgroundColor: "#4f46e5",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
  },
  addBtnText: {
    color: "#f9fafb",
    fontWeight: "600",
  },
  sectionLabel: {
    color: "#9ca3af",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 16,
    marginBottom: 8,
  },
  emptyText: {
    color: "#6b7280",
    fontSize: 14,
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 20,
  },
  questLibraryList: {
    flex: 1,
  },
  libraryQuestItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0f172a",
    borderRadius: 10,
    padding: 14,
    marginBottom: 8,
  },
  libraryQuestInfo: {
    flex: 1,
  },
  libraryQuestLabel: {
    color: "#f9fafb",
    fontSize: 16,
    fontWeight: "600",
  },
  libraryQuestMeta: {
    color: "#9ca3af",
    fontSize: 12,
    marginTop: 2,
  },
  libraryQuestArrow: {
    color: "#4f46e5",
    fontSize: 18,
  },
  libraryQuestBadge: {
    color: "#6b7280",
    fontSize: 11,
    backgroundColor: "#1f2937",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 4,
  },
  historyStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
  },
  historyStat: {
    alignItems: "center",
  },
  historyStatValue: {
    color: "#fbbf24",
    fontSize: 24,
    fontWeight: "700",
  },
  historyStatLabel: {
    color: "#9ca3af",
    fontSize: 11,
    textTransform: "uppercase",
    marginTop: 2,
  },
  exportControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
  },
  exportBtn: {
    backgroundColor: "#1f2937",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
  },
  exportBtnText: {
    color: "#e5e7eb",
    fontSize: 12,
  },
  historyList: {
    flex: 1,
  },
  historyEchoList: {
    marginTop: 12,
    marginBottom: 4,
    gap: 4,
  },
  historyEchoItem: {
    fontSize: 13,
    fontWeight: "600",
    opacity: 0.8,
  },
  historyDateHeader: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
    marginTop: 16,
    marginBottom: 8,
  },
  historySessionItem: {
    backgroundColor: "#0f172a",
    borderRadius: 8,
    padding: 12,
    marginBottom: 6,
  },
  historySessionTitle: {
    color: "#f9fafb",
    fontSize: 14,
    fontWeight: "500",
  },
  historySessionMeta: {
    color: "#9ca3af",
    fontSize: 12,
    marginTop: 2,
  },
  historySessionNotes: {
    color: "#6b7280",
    fontSize: 12,
    fontStyle: "italic",
    marginTop: 4,
  },
  playerRankCard: {
    backgroundColor: "#1e1b4b",
    borderRadius: 12,
    padding: 20,
    alignItems: "center",
    marginVertical: 16,
    borderWidth: 2,
    borderColor: "#4f46e5",
  },
  playerRankLabel: {
    color: "#a5b4fc",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  playerRankValue: {
    color: "#fbbf24",
    fontSize: 48,
    fontWeight: "700",
  },
  playerRankExp: {
    color: "#9ca3af",
    fontSize: 14,
    marginTop: 4,
  },
  leaderboardList: {
    marginTop: 8,
  },
  leaderboardItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0f172a",
    borderRadius: 8,
    padding: 12,
    marginBottom: 6,
  },
  leaderboardItemPlayer: {
    backgroundColor: "#1e1b4b",
    borderWidth: 1,
    borderColor: "#4f46e5",
  },
  leaderboardRank: {
    color: "#fbbf24",
    fontSize: 16,
    fontWeight: "700",
    width: 40,
  },
  leaderboardInfo: {
    flex: 1,
  },
  leaderboardName: {
    color: "#f9fafb",
    fontSize: 14,
    fontWeight: "500",
  },
  leaderboardLevel: {
    color: "#9ca3af",
    fontSize: 12,
  },
  leaderboardExp: {
    color: "#22c55e",
    fontSize: 14,
    fontWeight: "600",
  },
  leaderboardNote: {
    color: "#6b7280",
    fontSize: 12,
    textAlign: "center",
    marginTop: 20,
    fontStyle: "italic",
  },
  settingsSection: {
    marginTop: 24,
  },
  settingsListContent: {
    paddingBottom: 24,
  },
  settingsSectionHeader: {
    marginTop: 18,
    marginBottom: 8,
  },
  settingsSectionHeaderTitle: {
    color: "#9ca3af",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  settingsSectionHeaderSubtitle: {
    color: "#6b7280",
    fontSize: 12,
    marginTop: 6,
    lineHeight: 16,
  },
  settingsGroup: {
    backgroundColor: "#0f172a",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#1f2937",
    overflow: "hidden",
  },
  settingsCell: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 14,
    minHeight: 44,
  },
  settingsCellIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    backgroundColor: "#334155",
  },
  settingsCellLabel: {
    color: "#e5e7eb",
    fontSize: 14,
    fontWeight: "500",
    flex: 1,
    paddingRight: 12,
  },
  settingsCellRight: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  settingsCellSeparator: {
    height: 1,
    backgroundColor: "#1f2937",
    marginLeft: 14,
  },
  settingsCellRightText: {
    color: "#9ca3af",
    fontSize: 13,
  },
  settingsCellRightCheck: {
    color: "#22c55e",
    fontSize: 16,
    fontWeight: "700",
  },
  settingsCellInput: {
    minWidth: 90,
    textAlign: "right",
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "#0b1220",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#1f2937",
    color: "#f9fafb",
    fontSize: 13,
  },
  settingsSectionTitle: {
    color: "#f9fafb",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 12,
  },
  settingsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  settingsLabel: {
    color: "#9ca3af",
    fontSize: 14,
    width: 60,
  },
  settingsInput: {
    flex: 1,
    backgroundColor: "#0f172a",
    borderRadius: 8,
    padding: 10,
    color: "#f9fafb",
    borderWidth: 1,
    borderColor: "#1f2937",
  },
  settingsDescription: {
    color: "#6b7280",
    fontSize: 13,
    marginBottom: 12,
  },
  settingsOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#0f172a",
    borderRadius: 8,
    padding: 12,
    marginBottom: 6,
  },
  settingsOptionText: {
    color: "#e5e7eb",
    fontSize: 14,
  },
  settingsOptionDisabled: {
    color: "#6b7280",
  },
  settingsOptionCheck: {
    color: "#22c55e",
    fontSize: 16,
  },
  settingsAbout: {
    color: "#6b7280",
    fontSize: 13,
    marginBottom: 4,
  },
  settingsQuoteItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0f172a",
    borderRadius: 8,
    padding: 10,
    marginBottom: 6,
  },
  settingsQuoteText: {
    flex: 1,
    color: "#e5e7eb",
    fontSize: 13,
    fontStyle: "italic",
  },
  settingsQuoteDelete: {
    padding: 6,
    marginLeft: 8,
  },
  settingsQuoteDeleteText: {
    color: "#ef4444",
    fontSize: 14,
  },
  // Profile screen styles
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  profileTitle: {
    color: "#e5e7eb",
    fontSize: 20,
    fontWeight: "700",
    flex: 1,
    textAlign: "center",
    marginRight: 60,
  },
  profileBackBtn: {
    padding: 8,
  },
  backBtnText: {
    color: "#6366f1",
    fontSize: 16,
    fontWeight: "600",
  },
  profileAvatarSection: {
    alignItems: "center",
    marginBottom: 24,
  },
  profileAvatarContainer: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: "#0f172a",
    borderWidth: 3,
    borderColor: "#4f46e5",
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  profileLevelBadge: {
    backgroundColor: "#4f46e5",
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: -12,
  },
  profileLevelText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  profileExp: {
    color: "#fbbf24",
    fontSize: 18,
    fontWeight: "700",
    marginTop: 8,
  },
  profileDominant: {
    color: "#9ca3af",
    fontSize: 14,
    marginTop: 4,
  },
  profileStatsSection: {
    alignItems: "center",
    marginBottom: 24,
  },
  profileStatBreakdown: {
    backgroundColor: "#0f172a",
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
  },
  profileStatRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  profileStatLabel: {
    color: "#9ca3af",
    fontSize: 12,
    width: 80,
  },
  profileStatBarBg: {
    flex: 1,
    height: 8,
    backgroundColor: "#1f2937",
    borderRadius: 4,
    marginHorizontal: 8,
    overflow: "hidden",
  },
  profileStatBar: {
    height: "100%",
    backgroundColor: "#6366f1",
    borderRadius: 4,
  },
  profileStatValue: {
    color: "#e5e7eb",
    fontSize: 12,
    fontWeight: "600",
    width: 50,
    textAlign: "right",
  },
  profileActivitySection: {
    marginBottom: 24,
  },
  profileQuestList: {
    backgroundColor: "#0f172a",
    borderRadius: 12,
    padding: 12,
  },
  profileQuestItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#1f2937",
  },
  profileQuestEmoji: {
    fontSize: 16,
    marginRight: 12,
  },
  profileQuestName: {
    color: "#e5e7eb",
    fontSize: 14,
  },
  profileSummary: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#0f172a",
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
  },
  profileSummaryStat: {
    alignItems: "center",
  },
  profileSummaryValue: {
    color: "#fbbf24",
    fontSize: 24,
    fontWeight: "700",
  },
  profileSummaryLabel: {
    color: "#9ca3af",
    fontSize: 12,
    marginTop: 4,
  },
});

export default styles;